const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .get('/', (req, res) => res.sendFile(path.join(__dirname,'index.html')))
  .get('/index.html', (req, res) => res.sendFile(path.join(__dirname,'index.html')))
  .get('/login.html', (req, res) => res.sendFile(path.join(__dirname,'login.html')))
  .get('/about.html', (req, res) => res.sendFile(path.join(__dirname,'about.html')))
  .get('/search.html', (req, res) => res.sendFile(path.join(__dirname,'search.html')))
  .get('/sign-up.html', (req, res) => res.sendFile(path.join(__dirname,'sign-up.html')))
  .get('/signed-in.html', (req, res) => res.sendFile(path.join(__dirname,'signed-in.html')))
  .get('/logout.html', (req, res) => res.sendFile(path.join(__dirname,'logout.html')))
  .get('/signed-up.html', (req, res) => res.sendFile(path.join(__dirname,'signed-up.html')))
  .get('/signed-in-about.html', (req, res) => res.sendFile(path.join(__dirname,'signed-in-about.html')))
  .get('/signed-in-search.html', (req, res) => res.sendFile(path.join(__dirname,'signed-in-search.html')))
  .get('/user-profile.html', (req, res) => res.sendFile(path.join(__dirname,'user-profile.html')))
  .get('/user-profile2.html', (req, res) => res.sendFile(path.join(__dirname,'user-profile2.html')))
  .get('/upload-meme.html', (req, res) => res.sendFile(path.join(__dirname,'upload-meme.html')))
  .get('/uploaded-meme.html', (req, res) => res.sendFile(path.join(__dirname,'uploaded-meme.html')))
  .get('/meme1.html', (req, res) => res.sendFile(path.join(__dirname,'meme1.html')))
  .get('/meme2.html', (req, res) => res.sendFile(path.join(__dirname,'meme2.html')))
  .get('/meme3.html', (req, res) => res.sendFile(path.join(__dirname,'meme3.html')))
  .get('/meme4.html', (req, res) => res.sendFile(path.join(__dirname,'meme4.html')))
  .get('/meme5.html', (req, res) => res.sendFile(path.join(__dirname,'meme5.html')))
  .get('/meme6.html', (req, res) => res.sendFile(path.join(__dirname,'meme6.html')))
  .get('/meme7.html', (req, res) => res.sendFile(path.join(__dirname,'meme7.html')))
  .get('/meme8.html', (req, res) => res.sendFile(path.join(__dirname,'meme8.html')))
  .get('/meme9.html', (req, res) => res.sendFile(path.join(__dirname,'meme9.html')))
  .get('/meme10.html', (req, res) => res.sendFile(path.join(__dirname,'meme10.html')))
  .get('/meme11.html', (req, res) => res.sendFile(path.join(__dirname,'meme11.html')))
  .get('/meme12.html', (req, res) => res.sendFile(path.join(__dirname,'meme12.html')))
  .get('/meme13.html', (req, res) => res.sendFile(path.join(__dirname,'meme13.html')))
  .get('/meme14.html', (req, res) => res.sendFile(path.join(__dirname,'meme14.html')))
  .get('/meme15.html', (req, res) => res.sendFile(path.join(__dirname,'meme15.html')))
  .get('/inaccessible-meme.html', (req, res) => res.sendFile(path.join(__dirname,'inaccessible-meme.html')))
  .get('/funny.html', (req, res) => res.sendFile(path.join(__dirname,'funny.html')))
  .get('/sad.html', (req, res) => res.sendFile(path.join(__dirname,'sad.html')))
  .get('/relationships.html', (req, res) => res.sendFile(path.join(__dirname,'relationships.html')))
  .get('/social.html', (req, res) => res.sendFile(path.join(__dirname,'social.html')))
  .get('/disgusting.html', (req, res) => res.sendFile(path.join(__dirname,'disgusting.html')))
  .get('/racists.html', (req, res) => res.sendFile(path.join(__dirname,'racists.html')))
  .get('/signed-in-funny.html', (req, res) => res.sendFile(path.join(__dirname,'signed-in-funny.html')))
  .get('/signed-in-sad.html', (req, res) => res.sendFile(path.join(__dirname,'signed-in-sad.html')))
  .get('/signed-in-relationships.html', (req, res) => res.sendFile(path.join(__dirname,'signed-in-relationships.html')))
  .get('/signed-in-social.html', (req, res) => res.sendFile(path.join(__dirname,'signed-in-social.html')))
  .get('/signed-in-disgusting.html', (req, res) => res.sendFile(path.join(__dirname,'signed-in-disgusting.html')))
  .get('/signed-in-racists.html', (req, res) => res.sendFile(path.join(__dirname,'signed-in-racists.html')))

  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
